### PR TITLE
Upgrade to JetBrains License Server 19340

### PR DESCRIPTION
**Pull request by casz**
~~No release notes yet~~ 😄

We could set up Travis cronjob to weekly check if checksum has changed?
Perhaps even send a pull request with the change to checksum and version?

### CODE REVIEW

**Comment by casz** [comment]
fixed signing 😄

**Comment by casz** [comment]
Release notes to boot: https://www.jetbrains.com/help/license_server/release_notes.html 🙌

Again thank you @crazy-max 🙇

**Comment by crazy-max** [comment]
Hi @casz, thanks for your support I will check this out.

**Comment by crazy-max** [comment]
@casz Done thanks for your contrib!

**Comment by casz** [comment]
@crazy-max least I can do, so thank you! 🙇

**Comment by casz** [comment]
❤️ Thank you for fast-forwarding instead of merge commit, I wasn't gonna say anything last time but I approve 👍

**Pull request merged**
